### ISSUE TITLE
哪些是基础服务

### ISSUE THREAD

**Issue by monyuan** [hfbin/LibraPlatform#2]
必须要先启动的

**Comment by hfbin** [comment]
libra-platform -- 必須要啓動的服務 
│  ├─libra-auth -- 认证授权服务
│  ├─libra-gateway -- 网关SpringCloud Gateway
│  ├─libra-ucpm -- 用户中心权限菜单服务
│  ├─libra-base -- 基础服务
│  ├─libra-tenant -- 租户服务
