### ISSUE TITLE
代码生成器这里报空指针异常

### ISSUE THREAD

**Issue by monyuan** [hfbin/LibraPlatform#3]
`// 查询表信息
			Map<String, String> table = generatorMapper.queryTable(data, genConfig.getDsName());`

这里返回的是null

**Comment by monyuan** [comment]
`==>  Preparing: select table_name tableName, engine, table_comment tableComment, create_time createTime from information_schema.tables where table_schema = (select database()) and table_name = ?
==> Parameters: test_user(String)
<==      Total: 0`

**Comment by monyuan** [comment]
直接执行sql的话是可以查到的，怀疑是不是SqlSession没切换过来？

**Comment by hfbin** [comment]
环境问题
